### ISSUE TITLE
Request for more info on Inventory

### ISSUE THREAD

**Issue by bibleuspro** [afrostalin/FireNET#1]
So far this seems to be the most complete game out there for CE that is also open source, only other stuff I can think of is humble bundle which you can't get anymore. And is not open source.

I saw a youtube video with one of your inventories. I did a quick look through the code and didn't see any flash ui for the inventory specifically. How functional is the inventory in this repo? Is it the same as the one on your youtube channel?

Also any load testing done? So far FireNET seems to be a chat api, with possibly trading built in or next planned. Can this also do typical MMO stuff yet? Like real time walking about with a friend online?

**Comment by afrostalin** [comment]
Hi.
First : Flash inventory it's my other project, currently it is not added, but it's planned in future.
Second : FireNET not "chat api" - it's master server for MMO games. Now he have : 
- Login system (You can login by login and password, you can use Redis and MySql database, also you can use php scripts for authorization)
- Profile system. All profile have parameters like : uid, nickname, fileModel, level, money and etc. You can create profile, you can get profile by login and password in login system
- Friends system. You can send friend invite to other player by nickname, you have decline or accept invite and add friend to list
- Shop and storage system. You can get shop items from shop.xml script. You can buy item (if you have money and you level > minimal level for buying). You can get list you profiles items
- Matchmaking system. You can register you game server in FireNET game server list. You can get game server by map name, gamerules or server name . You can join in you server and play with you friends (If you have dedicated machine with real ip address)

Now i work with integration in game server (load specific character model and inventory from FireNET)
In future i start work with Flash UI (Storage, shop, friends, and in-game inventory)
I hope that explains everything.

**Comment by bibleuspro** [comment]
Great, I am excited to see the inventory.

I am interested in the MySQL, and have another question. I will ask here but also can open another issue if you prefer to keep things on topic.

For MySQL:
I saw here https://github.com/afrostalin/FireNET/wiki/%5BFireNET%5D-Console-variables-and-commands
that setting it to use MySQL is easy. The question is, how do I send/receive data to it. Like will your inventory example pull from database fields then, this would be ideal for my use, curious what you had planned.

Thanks for your hard work on this. Looks great.

**Comment by afrostalin** [comment]
1. You need integrate FireNET module to cryengine (https://github.com/afrostalin/FireNET/wiki/%5BCryEngine-Module%5D-Integration-to-CryEngine-(Automatic))
2. You need setup server to work with MySQL. Open bin/WIN64/debug folder and change server.cfg
   db_mode = MySql

mysql_host = 127.0.0.1

mysql_port = 3306 

mysql_db_name = db name

mysql_username = user

mysql_password = password
1. You need : 
   - New flowgraph node in cryengine module to send new query to FireNET (FlowNodes.cpp)
   - Add you packet in packet type selection (tcpconnection.cpp - > void ReadyRed())
   - New read function in FireNET (clientquerys.h + clientquerys.cpp)
   - New database function to send you data in MySQL (dbworker.h + dbworker.cpp)

It sounds complicated by the description, but it is actually quite easy to do looking at how these classes are arranged.
Or you can wait a little while I'll add a detailed lesson on the WIKI
